version: '3.8'
services:
  db:
    image: postgres:13.3
    environment:
      - "POSTGRES_DB=flask-vue-crud-db"
      - "POSTGRES_PASSWORD=sample_pass"
      - "POSTGRES_USER=postgres"
      - "PGDATA=/var/lib/postgresql/data/flask-vue-crud-db"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d flask-vue-crud-db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    command: [ "postgres", "-c", "log_statement=all" ]

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db
      - mongo-config:/data/configdb

volumes:
  db-data:
  mongo-config:

#  server:
#    build: ./server
#    ports:
#      - "5000:5000"
#    networks:
#      default:
#        aliases:
#          - server
#
#  client:
#    build: ./client
#    ports:
#      - "3000:5000"
#    links:
#      - server
#    networks:
#      default:
#        aliases:
#          - client
